travis:
  secure:
    BINSTAR_TOKEN: XVV2Sp8YHJPcTuypfOAQCq5wbpw5gNzCP0QY5vctqZy+TvsRBTpoZNiIoSW5Yq2UbAxtLaymQnkjo8CXlY83GZIFCr/51nFgT1EoLdg6aNv7ClBoLTPYbC1yetRvV90CFxHzAXPaRFZjIkkT12wV4LTjJsI0Ag4c0TS6t+hI6FlpbNR/+Rs0jmZYdhZrcOdswwWUmr17T9h3bSREUcK6L/ateYBogbcEGAsb6+etv2EW9i6hIYpCn1eMcARoAFBIA4/MWW5HBaEDQAdQdfLNpcsuyrlS/w+eGI+DTUifWidj/GoW/m6VHR4KNMwmsZtsaTRyDimrlFEsV7Cu28c6wLnT4WbjF5c1yZMmqOw6jEaEiZhCqoYKDh2tiuUWv9P/+hGgbBZiRZEsnErMMBoT5m8e/ykzHPTw9dfEnUBHHK9CCDKHv81EoCjqS0CYOClAV7QG3YIOcI7no1snSY+IFRVFStBWYD3wfaUJ4gtovkgCl6xsS6YPLIsWxCSG6m9H1nDvXKeg6qb4tTN+DGS3nat1A9FfSZcy1zv9hFv2F7+LGKLX+LlAeKcqEKjIRdk0uViGA+oIZ+RdT/KT3NjLL3/mhpI0QcoOIPqj9WW6ts5j8xYlg5jIv4d1OY4dqRVGlya+Fntb3PXZSheN2Fbnl47g10/LBmvjh/zL4JS9tJ0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
