travis:
  secure:
    BINSTAR_TOKEN: bj82vvkVPbdNNUJ+ucunW8/WWqM4XupCfn8vCBssfPKg1Ssc7b5ArEEl4hG6eRLcFTp1kb0fiPC30doD8GjcEWKCzPHpQxQX+z4y1jOAyltXWdmDbKs9mnbV1lS0Jl/4TkxuG3RLM2sKVus3FM0+uCeQ7tLZHVlTiexDbcA6kRXz6LlFh2f1/AJd1LdR1MeA037vJL2wLnCH8kY7qMVRSpCesCAqC5+R0d1oRSgBKBgZA8JZlYGmg4lOvpnFeLkcuqhnxRRw865+TjQyaUaCptNfKIL4Jm7hjkChRQxz+kO3UsFydV/ccvojKCtlYKfXrbxTjt9NVbdaf4aB1Tv/t5umvTi8wddU0fVqTdDEL2yADvDnwQEcK+DVpS1Ct0SeeQ+lqjAJJtuQWISLkahmimVM2Bd+t8AU6mp7DjzeyE++tBTuaTDirn44UfHVJepXjtoAuTMpRxwsXDcmevFqduRnLUrv0ZBd6F7BZwJNKr+Y8xpmip8gMwqU4VCDmHXbq7AQIOOt8S8wqMShNu1Hl7Tf1Lt1uzoNXQXLRVfgc7RZy+X00wHZ6318BhhyHiB0fw6j1kmSgY9gn1/9GfYdI9YNcJoS9xULOlESubM+q0JvLi9VSnQ6XPR2JGWqqEbIkISZvOom8bbbrfm1WxL2znVVpOELQM1jkvzO5OdKF5M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
