travis:
  secure:
    BINSTAR_TOKEN: CRldRaNLAk0e6MQ+kaARMF63SW6qVOFxHMNgeWdAa+2q2P+GbjJynap+x7dLOhCm8WRt/8XBN96M7jsCVYq6eE2bnB8n+B6QEmzhgB4kWsE/o1mwzYj5P29mGJmw3njYZgSNWOTSsFRJH8qqkwAIWo67dvRC3lVDhy0+ZWe3UREOiPK9L8kCvc1kcGCR+j0z2JeT4B2OuhP8rMw44VDXeYb7Ok+BU8Ud/PYV4puMH7vLROKv3xc2HZgdSHi6GohK+qDEDIrzkIRMv4n1mXXuaOOG/wx60BFjZiUTYm4kJctYIwBFLIRmoXeJBGBgIwoSBLb9ygf+u1Fg2jB7kPlgTlYvUSKWmUqO6B40vSCztstk3wg7kFyU+EI0C1kXLLQGkauN4pQ+svAniHI+m9jjxNi7LFusIkhKDvaHqNrUN1XOsEyzKTd+W5mMKm55RoDOZju7w2N0H5dtK+4jT+PYwL1/5C3Z1G2aL9lFQvU11bYCdTzGTFWlhiHlTfY4ijK1mYQAdU5ujzZKGfaCZ8ozquqUK7smexAbFDTLSRFi/ZjOyfv0pSQw1HZe9ZU1GRxToWTu0NTi8swPnkUtGNIpDKWhS6Lew4QPVR8+LHaOKS341X11a+n25RmZIkLoy5dBB4+Ete3eSHjykpVsac3EYAExsUTLENBwpFmNBpxxETo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
